export const content = {
  welcome: {
    logoAlt: 'Logotipo de Moviefy',
    title: 'Moviefy',
    headline: 'Empieza a disfrutar de las mejores películas y series en un solo lugar.',
    subtitle: 'Todo el entretenimiento que buscas, adaptado a ti.',
    cta: 'Explorar Películas',
    disclaimer: 'La disponibilidad de los títulos varía según el país. Mayor de 18 años.',
    footer: '© Moviefy Platform',
  },
  exploration: {
    title: 'Exploración de películas',
    moviesSectionTitle: 'Películas',
    searchResultsTitle: (query) => `Resultados para "${query}"`,
  },
  search: {
    ariaLabel: 'Buscar películas',
    placeholder: 'Buscar películas por título…',
    clearAriaLabel: 'Limpiar búsqueda',
  },
  filters: {
    ariaLabel: 'Filtros de películas',
    genreLabel: 'Género',
    genreAll: 'Todos los géneros',
    ratingLabel: 'Valoración',
    ratingAny: 'Cualquier valoración',
    ratingOption: (n) => `${n}+ estrellas`,
    sortLabel: 'Ordenar por',
    sortTrending: 'Tendencia',
    sortTopRated: 'Mejor valoradas',
    sortRecent: 'Más recientes',
    clearAll: 'Limpiar filtros',
  },
  hero: {
    carouselAriaLabel: 'Películas destacadas',
    playCta: 'Reproducir',
    moreInfoCta: 'Más información',
    ratingAriaLabel: (rating) => `Puntuación ${rating} sobre 10`,
    goToSlideAriaLabel: (n) => `Ir al slide ${n}`,
    noBackdrop: 'Sin imagen',
  },
  underConstruction: {
    title: 'En construcción',
    message: 'Esta sección estará disponible próximamente.',
  },
  nav: {
    ariaLabel: 'Navegación principal',
    home: 'Inicio',
    exploration: 'Explorar',
    favorites: 'Favoritas',
    profile: 'Perfil',
    about: 'Acerca de',
    logoAlt: 'Logotipo de Moviefy',
    brand: 'Moviefy',
    searchAriaLabel: 'Buscar',
    notificationsAriaLabel: 'Notificaciones',
    profileMenuAriaLabel: 'Menú de perfil',
  },
  footer: {
    ariaLabel: 'Pie de página',
    copyright: '© 2026 Moviefy Platform',
    tmdbCta: 'Información sobre TMDB y Moviefy',
    socialAriaLabel: 'Redes sociales',
    social: {
      instagram: { url: '#', label: 'Instagram' },
      twitter: { url: '#', label: 'X (antes Twitter)' },
      youtube: { url: '#', label: 'YouTube' },
      github: { url: '#', label: 'GitHub' },
    },
  },
  about: {
    title: 'Acerca de Moviefy',
    intro:
      'Moviefy es una aplicación para descubrir, explorar y guardar tus películas favoritas. Proyecto final individual del bootcamp FemCoders en Factoría F5.',
    tmdbSectionTitle: 'Datos de películas',
    tmdbAttribution:
      'Este producto utiliza la API de TMDB, pero no está respaldado ni certificado por TMDB.',
    tmdbVisitCta: 'Visitar TMDB',
    tmdbUrl: 'https://www.themoviedb.org',
  },
  states: {
    loading: 'Cargando películas…',
    emptyTitle: 'No hay películas',
    emptyMessage: 'No encontramos resultados. Prueba con otra búsqueda u otro filtro.',
    emptySearchTitle: 'Sin resultados',
    emptySearchMessage: (query) =>
      `No encontramos películas para "${query}". Prueba con otro título.`,
    errorTitle: 'Algo salió mal',
    errorMessage: 'No pudimos cargar las películas. Vuelve a intentarlo.',
    retry: 'Reintentar',
    loadingMore: 'Cargando más películas…',
    loadMoreError: 'No pudimos cargar más resultados.',
    endOfResults: 'Has llegado al final.',
  },
  movies: {
    posterAlt: (title) => `Cartel de ${title}`,
    noPoster: 'Sin cartel',
    noYear: 'Año desconocido',
    ratingAriaLabel: (rating) => `Puntuación ${rating} sobre 10`,
  },
  personDetail: {
    roleActor: 'Actor / Actriz',
    roleDirector: 'Director / Directora',
    backCta: 'Volver',
    bornLabel: 'Nacimiento',
    diedLabel: 'Fallecimiento',
    placeLabel: 'Lugar de nacimiento',
    biographyTitle: 'Biografía',
    noBiography: 'Sin biografía disponible.',
    actingFilmographyTitle: 'Películas como actor o actriz',
    directingFilmographyTitle: 'Películas dirigidas',
    noCredits: 'Sin créditos disponibles.',
    notFoundTitle: 'Persona no encontrada',
    notFoundMessage: 'No encontramos a la persona que buscas.',
    notFoundCta: 'Volver a explorar',
    profileAlt: (name) => `Foto de ${name}`,
    noProfile: 'Sin foto',
  },
  movieDetail: {
    backCta: 'Volver',
    runtimeLabel: (min) => `${min} min`,
    overviewTitle: 'Sinopsis',
    noOverview: 'Sin sinopsis disponible.',
    castTitle: 'Reparto',
    noCast: 'Sin información de reparto.',
    directorTitle: 'Dirección',
    directorTitlePlural: 'Dirección',
    noDirector: 'Sin información de dirección.',
    profileAlt: (name) => `Foto de ${name}`,
    noProfile: 'Sin foto',
    notFoundTitle: 'Película no encontrada',
    notFoundMessage: 'No encontramos la película que buscas.',
    notFoundCta: 'Volver a explorar',
    backdropAlt: (title) => `Imagen de fondo de ${title}`,
  },
}
